Added early support for creating Xenial containers

diff --git a/scripts/ontheroad-cli b/scripts/ontheroad-cli
--- a/scripts/ontheroad-cli
+++ b/scripts/ontheroad-cli
@@ -40,146 +40,255 @@ do
 
 	if [ "$input" == "1" ]; then
 
-		if [ ! -s ~/.cache/ontheroad.emanuelesorce/containers/rootfs.tar.bz2 ]; then
+		clear
+		echo "--------------------"
+		echo "Create new container"
+		echo
+		echo "Select the distro:"
+		echo "Note that using xenial on vivid works, but using vivid on xenial probably not"
+		echo
+		echo "1) Ubuntu Vivid 15.04"
+		echo "2) Ubuntu Xenial 16.04"
 
-			clear
-			echo "----------------------"
-			echo "Create a new container"
-			echo
-			echo "Container not downloaded"
-			echo "Download is approximately of ~170Mb"
-			echo "The downloaded image is an already debootstrapped container ready to be installed"
-			echo "The download is required only once, then you'll be able to quickly setup as many containers as you want offline"
-			echo
-			echo "press 'i' to download it"
-			echo
+		read distro
 
-			read input2
+		if [ "$distro" == "1" ]; then
 
-			if [ "$input2" == "i" ]; then
+			if [ ! -s ~/.cache/ontheroad.emanuelesorce/containers/rootfs.tar.bz2 ]; then
 
 				clear
-				echo "----------------"
-				echo "Downloading..."
+				echo "--------------------------"
+				echo "Create new vivid container"
 				echo
-				echo "log:"
+				echo "Vivid container not downloaded"
+				echo "Download is approximately of ~170Mb"
+				echo "The downloaded image is an already debootstrapped container ready to be installed"
+				echo "The download is required only once, after you'll be able to quickly setup as many Vivid containers as you want offline"
+				echo "note that a Vivid container probably won't work on Xenial!"
+				echo
+				echo "press 'i' to download it"
 				echo
 
-				mkdir ~/.cache/ontheroad.emanuelesorce/containers/
-				cd ~/.cache/ontheroad.emanuelesorce/containers
+				read input2
 
-				wget $( /opt/click.ubuntu.com/ontheroad.emanuelesorce/current/curl -s https://api.github.com/repos/tronfortytwo/ontheroad/releases/latest | grep "browser_" | cut -d\" -f4)
-
-				if [ $? -eq 0 ]; then
+				if [ "$input2" == "i" ]; then
 
 					clear
-					echo "--------------------"
-					echo "Contaner successfully downloaded!"
+					echo "----------------"
+					echo "Downloading..."
 					echo
-					echo "Now you can create new containers"
+					echo "log:"
 					echo
-					echo "press enter to continue"
 
-					read qwe
+					mkdir ~/.cache/ontheroad.emanuelesorce/containers/
+					cd ~/.cache/ontheroad.emanuelesorce/containers
 
-				else
+					wget $( /opt/click.ubuntu.com/ontheroad.emanuelesorce/current/curl -s https://api.github.com/repos/tronfortytwo/ontheroad/releases/latest | grep "browser_" | cut -d\" -f4)
 
-					rm -r ~/.cache/ontheroad.emanuelesorce/containers
-					echo
-					echo "------------------"
-					echo "Container download failed"
-					echo
-					echo "press enter to continue"
+					if [ $? -eq 0 ]; then
 
-					read qwee
+						clear
+						echo "--------------------"
+						echo "Contaner successfully downloaded!"
+						echo
+						echo "Now you can create new vivid containers"
+						echo
+						echo "press enter to continue"
+						read qwe
+					else
+						rm -r ~/.cache/ontheroad.emanuelesorce/containers/rootfs*
+						echo
+						echo "------------------"
+						echo "Container download failed"
+						echo
+						echo "press enter to continue"
+						read qwee
+					fi
 				fi
-			fi
-		else
-
-			clear
-			echo "----------------------"
-			echo "Create a new container"
-			echo
-			echo "Insert a name for the new container:"
-			echo "Name must be of form ([a-z0-9][a-z0-9+.-]+)."
-			echo
-			read newname
-			clear
-			if [ -d "/home/phablet/.cache/libertine-container/$newname/rootfs" ]; then
-				clear
-				echo "----------------------------"
-				echo "The container already exits!"
-				echo
-				echo "Press something to continue..."
-				read -n 1 -s
 			else
 				clear
 				echo "----------------------------"
-				echo "Installing the new container"
+				echo "Create a new vivid container"
 				echo
-				echo "This could take few minutes. There is no need for an internet connection."
-				echo "Creating into: /home/phablet/.cache/libertine-container/$newname"
+				echo "Insert a name for the new container:"
+				echo "Name must be of form ([a-z0-9][a-z0-9+.-]+)."
 				echo
-				echo "log:"
-				echo
-				mkdir -p "/home/phablet/.cache/libertine-container/$newname"
-				cp -v ~/.cache/ontheroad.emanuelesorce/containers/rootfs.tar.bz2 "/home/phablet/.cache/libertine-container/$newname/"
-				bzip2 -d  "/home/phablet/.cache/libertine-container/$newname/rootfs.tar.bz2"
-				tar xvf "/home/phablet/.cache/libertine-container/$newname/rootfs.tar" -C "/home/phablet/.cache/libertine-container/$newname/"
-				rm "/home/phablet/.cache/libertine-container/$newname/rootfs.tar"
-
-				sed -i '/This file is automatically generated by Libertine/d' ~/.local/share/libertine/ContainersConfig.json
-
-				LINES=$(wc -l < ~/.local/share/libertine/ContainersConfig.json)
-				if [ "$LINES" == "3" ]; then
-					rm ~/.local/share/libertine/ContainersConfig.json
-					touch ~/.local/share/libertine/ContainersConfig.json
-				fi
-
-				if [ ! -s ~/.local/share/libertine/ContainersConfig.json ]; then
-					touch ~/.cache/ontheroad.emanuelesorce/temp/isnew
-					echo "{" > ~/.local/share/libertine/ContainersConfig.json
-					echo "    \"containerList\": [" >> ~/.local/share/libertine/ContainersConfig.json
-					echo "    ]," >> ~/.local/share/libertine/ContainersConfig.json
-					echo "   \"defaultContainer\":\"$newname\"" >> ~/.local/share/libertine/ContainersConfig.json
-					echo "}" >> ~/.local/share/libertine/ContainersConfig.json
-				fi
-				mkdir ~/.cache/ontheroad.emanuelesorce/temp
-				cp -v ~/.local/share/libertine/ContainersConfig.json ~/.cache/ontheroad.emanuelesorce/temp/
-				sed -n '1,2p' ~/.cache/ontheroad.emanuelesorce/temp/ContainersConfig.json > ~/.local/share/libertine/ContainersConfig.json
-				echo "        {" >> ~/.local/share/libertine/ContainersConfig.json
-				echo "            \"distro\": \"vivid\"," >> ~/.local/share/libertine/ContainersConfig.json
-				echo "            \"id\": \"$newname\"," >> ~/.local/share/libertine/ContainersConfig.json
-				echo "            \"InstallStatus\": \"ready\"," >> ~/.local/share/libertine/ContainersConfig.json
-				echo "            \"InstalledApps\": []," >> ~/.local/share/libertine/ContainersConfig.json
-				echo "            \"multiarch\": \"disabled\"," >> ~/.local/share/libertine/ContainersConfig.json
-				echo "            \"name\": \"OnTheRoad-$newname\"," >> ~/.local/share/libertine/ContainersConfig.json
-				echo "            \"type\": \"chroot\"" >> ~/.local/share/libertine/ContainersConfig.json
-
-				if [ -f ~/.cache/ontheroad.emanuelesorce/temp/isnew ]; then
-					echo "        }" >> ~/.local/share/libertine/ContainersConfig.json
-					rm ~/.cache/ontheroad.emanuelesorce/temp/isnew
-				else
-					echo "        }," >> ~/.local/share/libertine/ContainersConfig.json
-				fi
-				sed -n '3,$p' ~/.cache/ontheroad.emanuelesorce/temp/ContainersConfig.json >> ~/.local/share/libertine/ContainersConfig.json
-				rm ~/.cache/ontheroad.emanuelesorce/temp/ContainersConfig.json
-
+				read newname
+				clear
 				if [ -d "/home/phablet/.cache/libertine-container/$newname/rootfs" ]; then
 					clear
-					echo "------------------------------"
-					echo "Container created successfully"
+					echo "----------------------------"
+					echo "The container already exits!"
 					echo
 					echo "Press something to continue..."
 					read -n 1 -s
 				else
-					rm -r "/home/phablet/.cache/libertine-container/$newname"
 					clear
-					echo "-------------------------------------------"
-					echo "Error occurred while creating the container"
+					echo "----------------------------"
+					echo "Installing the new container"
 					echo
-					echo "Press something to continue..."
-					read -n 1 -s
+					echo "This could take few minutes. There is no need for an internet connection."
+					echo "Creating into: /home/phablet/.cache/libertine-container/$newname"
+					echo
+					echo "log:"
+					echo
+					mkdir -p "/home/phablet/.cache/libertine-container/$newname"
+					cp -v ~/.cache/ontheroad.emanuelesorce/containers/rootfs.tar.bz2 "/home/phablet/.cache/libertine-container/$newname/"
+					bzip2 -d  "/home/phablet/.cache/libertine-container/$newname/rootfs.tar.bz2"
+					tar xvf "/home/phablet/.cache/libertine-container/$newname/rootfs.tar" -C "/home/phablet/.cache/libertine-container/$newname/"
+					rm "/home/phablet/.cache/libertine-container/$newname/rootfs.tar"
+
+					sed -i '/This file is automatically generated by Libertine/d' ~/.local/share/libertine/ContainersConfig.json
+
+					LINES=$(wc -l < ~/.local/share/libertine/ContainersConfig.json)
+					if [ "$LINES" == "3" ]; then
+						rm ~/.local/share/libertine/ContainersConfig.json
+						touch ~/.local/share/libertine/ContainersConfig.json
+					fi
+
+					if [ ! -s ~/.local/share/libertine/ContainersConfig.json ]; then
+						touch ~/.cache/ontheroad.emanuelesorce/temp/isnew
+						echo "{" > ~/.local/share/libertine/ContainersConfig.json
+						echo "    \"containerList\": [" >> ~/.local/share/libertine/ContainersConfig.json
+						echo "    ]," >> ~/.local/share/libertine/ContainersConfig.json
+						echo "   \"defaultContainer\":\"$newname\"" >> ~/.local/share/libertine/ContainersConfig.json
+						echo "}" >> ~/.local/share/libertine/ContainersConfig.json
+					fi
+					mkdir ~/.cache/ontheroad.emanuelesorce/temp
+					cp -v ~/.local/share/libertine/ContainersConfig.json ~/.cache/ontheroad.emanuelesorce/temp/
+					sed -n '1,2p' ~/.cache/ontheroad.emanuelesorce/temp/ContainersConfig.json > ~/.local/share/libertine/ContainersConfig.json
+					echo "        {" >> ~/.local/share/libertine/ContainersConfig.json
+					echo "            \"distro\": \"vivid\"," >> ~/.local/share/libertine/ContainersConfig.json
+					echo "            \"id\": \"$newname\"," >> ~/.local/share/libertine/ContainersConfig.json
+					echo "            \"InstallStatus\": \"ready\"," >> ~/.local/share/libertine/ContainersConfig.json
+					echo "            \"InstalledApps\": []," >> ~/.local/share/libertine/ContainersConfig.json
+					echo "            \"multiarch\": \"disabled\"," >> ~/.local/share/libertine/ContainersConfig.json
+					echo "            \"name\": \"OnTheRoad-$newname\"," >> ~/.local/share/libertine/ContainersConfig.json
+					echo "            \"type\": \"chroot\"" >> ~/.local/share/libertine/ContainersConfig.json
+
+					if [ -f ~/.cache/ontheroad.emanuelesorce/temp/isnew ]; then
+						echo "        }" >> ~/.local/share/libertine/ContainersConfig.json
+						rm ~/.cache/ontheroad.emanuelesorce/temp/isnew
+					else
+						echo "        }," >> ~/.local/share/libertine/ContainersConfig.json
+					fi
+					sed -n '3,$p' ~/.cache/ontheroad.emanuelesorce/temp/ContainersConfig.json >> ~/.local/share/libertine/ContainersConfig.json
+					rm ~/.cache/ontheroad.emanuelesorce/temp/ContainersConfig.json
+
+					if [ -d "/home/phablet/.cache/libertine-container/$newname/rootfs" ]; then
+						clear
+						echo "------------------------------"
+						echo "Container created successfully"
+						echo
+						echo "Press something to continue..."
+						read -n 1 -s
+					else
+						rm -r "/home/phablet/.cache/libertine-container/$newname"
+						clear
+						echo "-------------------------------------------"
+						echo "Error occurred while creating the container"
+						echo
+						echo "Press something to continue..."
+						read -n 1 -s
+					fi
+				fi
+			fi
+		fi
+		if [ "$distro" == "2" ]; then
+
+			if [ ! -s ~/.cache/ontheroad.emanuelesorce/containers/xenial.tar.bz2 ]; then
+				clear
+				echo "-----------------------------"
+				echo "Create a new Xenial container"
+				echo
+				echo "Download is approximately of ~90Mb"
+                echo "The downloaded image is an already debootstrapped Xenial container ready to be installed"
+                echo "The download is required only once, after you'll be able to quickly setup as many Xenial containers as you want offline"
+				echo "Note that, while vivid container can be used without sudo, Xenial containers need sudo because they not rely on Libertine"
+				echo
+				echo "press 'i' to download"
+
+				read download
+
+				if [ "$download" == "i" ]; then
+
+                    clear
+                    echo "----------------"
+                    echo "Downloading..."
+                    echo
+                    echo "log:"
+                    echo
+
+                    mkdir ~/.cache/ontheroad.emanuelesorce/containers/
+                    cd ~/.cache/ontheroad.emanuelesorce/containers
+
+                    wget $( /opt/click.ubuntu.com/ontheroad.emanuelesorce/current/curl -s https://api.github.com/repos/tronfortytwo/xontheroad/releases/latest | grep "browser_" | cut -d\" -f4)
+
+                    if [ $? -eq 0 ]; then
+                        clear
+                        echo "--------------------"
+                        echo "Contaner successfully downloaded!"
+                        echo
+                        echo "Now you can create new Xenial containers"
+                        echo
+                        echo "press enter to continue"
+                        read qwe
+                    else
+                        rm ~/.cache/ontheroad.emanuelesorce/containers/xenial*
+                        echo
+                        echo "------------------"
+                        echo "Container download failed"
+                        echo
+					fi
+				fi
+			else
+				clear
+				echo "---------------------------"
+				echo "Create new Xenial container"
+                echo
+                echo "Insert a name for the new container:"
+                echo "Don't use spaces"
+                echo
+                read newname
+                clear
+                if [ -d "/home/phablet/.local/share/ontheroad.emanuelesorce/$newname" ]; then
+                    clear
+                    echo "----------------------------"
+                    echo "The container already exits!"
+                    echo
+                    echo "Press something to continue..."
+                    read -n 1 -s
+                else
+                    clear
+                    echo "----------------------------"
+                    echo "Installing the new container"
+                    echo
+                    echo "This could take few minutes. There is no need for an internet connection."
+                    echo "Creating into: ~/.local/share/ontheroad.emanuelesorce/$newname"
+                    echo
+                    echo "log:"
+                    echo
+                    mkdir -p ~/.local/share/ontheroad.emanuelesorce/
+                    cp -v ~/.cache/ontheroad.emanuelesorce/containers/xenial.tar.bz2 ~/.local/share/ontheroad.emanuelesorce
+                    bzip2 -d  ~/.local/share/ontheroad.emanuelesorce/xenial.tar.bz2
+                    tar xvf ~/.local/share/ontheroad.emanuelesorce/xenial.tar -C ~/.local/share/ontheroad.emanuelesorce
+					mv -r ~/.local/share/ontheroad.emanuelesorce/xenial0 ~/.local/share/ontheroad.emanuelesorce/"$newname"
+                    rm ~/.local/share/ontheroad.emanuelesorce/xenial.tar
+					if [ -d "/home/phablet/.local/share/ontheroad.emanuelesorce/$newname" ]; then
+						clear
+						echo "---------------------"
+						echo "New container created"
+						echo
+						echo "Press something to continue..."
+						read -n 1 -s
+					else
+						rm -rf "/home/phablet/.local/share/ontheroad.emanuelesorce/$newname"
+						echo "-----------------------------"
+						echo "New container creation failed"
+						echo
+						echo "Press something to continue..."
+						read -n 1 -s
+					fi
 				fi
 			fi
 		fi
@@ -189,9 +298,10 @@ do
 		clear
 		echo "On The Road Manual"
 		echo "------------------"
-		echo "On The Road uses chroot containers to have environments where the hacker can develop freely"
+		echo "On The Road uses chroot containers to have environments where the hacker can develop freely."
 		echo "To create a new container, select Create New Container in the main menu then follow instructions."
-		echo "Once a container is created you can use it going in the Use Container section of the main menu, there you can set up a developing workflow installing Clickable automatically and open shells"
+		echo "Once a container is created you can use it going in the Use Container section of the main menu, there you can set up a developing workflow installing Clickable automatically and open shells."
+		echo "You can create both Xenial (16.04) and Vivid (15.04) containers. Xenial ones requires root privilegies, and Vivid containers only work on vivid images (<= OTA 3)."
 		echo "Another point is the seamless integration with Libertine, you can use your Libertine containers with On The Road out of the box, and viceversa if you wish"
 		echo "If you plan to use otr remotely (from a computer throught ssh, adb, phablet-shell) or from a Iperspace session, use the otr-adb command instead"
 		echo
